#install development packages
install-repository-packages:
    @sudo pacman -Syu --noconfirm
    @echo "Installing terminal configuration tools"
    @sudo pacman -S --noconfirm alacritty zellij yazi neovim fish fisher zoxide
    @sudo chsh -s /usr/bin/fish
    @curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install
    @echo "Installing container tools"
    @sudo pacman -S --noconfirm docker docker-compose podman unzip
    @sudo pacman -Syu --noconfirm
    @echo "Installing utility tools"
    @sudo pacman -S --noconfirm audacity obs-studio

#install yay
install-yay:
    @rm -rf yay-bin && sudo pacman -S --needed --noconfirm git base-devel && git clone https://aur.archlinux.org/yay-bin.git && cd yay-bin && makepkg -si && cd .. && rm -rf yay-bin

#install AUR packages
install-aur-packages: install-yay
    @echo "Installing asdf for programming languages"
    @yay -S asdf-vm
    @echo "Installing utility tools"
    @yay -S zen-browser-avx2-bin crow-translate

install-all-tools: install-repository-packages install-aur-packages
    @echo "All tools installed!"

#configure tools
configure-tools:
    @echo "configure terminal tools"
    echo "set -g -x fish_greeting ''" >> ~/.config/fish/config.fish
    echo "alias v \"nvim\"" >> ~/.config/fish/config.fish
    echo "alias x \"exit\"" >> ~/.config/fish/config.fish
    echo "alias lg \"lazygit\"" >> ~/.config/fish/config.fish
    echo "source /opt/asdf-vm/asdf.fish" >> ~/.config/fish/config.fish
    echo "zoxide init fish | source" >> ~/.config/fish/config.fish

#install programming languages
#install-programming-languages:
#    @echo "Installing asdf plugins"
#    @asdf plugin-add nodejs
#    @asdf plugin-add golang
#    @echo "Installing asdf programming languages"
#    @asdf install nodejs latest
#    @asdf install golang latest
