#install development packages
install-repository-packages:
    @sudo pacman -Syu --noconfirm
    @echo "Installing terminal configuration tools"
    @sudo pacman -S --noconfirm alacritty zellij yazi neovim fish fisher zoxide lazygit ghostty mise wl-clipboard tree-sitter-cli fzf usage
    @sudo chsh -s /usr/bin/fish
    @echo "Installing container tools"
    @sudo pacman -S --noconfirm docker docker-compose podman unzip
    @sudo pacman -Syu --noconfirm
    @echo "Installing utility tools"
    @sudo pacman -S --noconfirm audacity obs-studio

#install yay
install-yay:
    @rm -rf yay-bin && sudo pacman -S --needed --noconfirm git base-devel && git clone https://aur.archlinux.org/yay-bin.git && cd yay-bin && makepkg -si && cd .. && rm -rf yay-bin

#install AUR packages
install-aur-packages: install-yay
    @echo "Installing utility tools"
    @yay -S zen-browser-bin
    @yay -S pacseek

install-all-tools: install-repository-packages install-aur-packages
    @echo "All tools installed!"

#configure tools
configure-tools:
    @echo "configure terminal tools"
    @fish
    @exit
    @command -v fish | sudo tee -a /etc/shells
    @chsh -s "$(command -v fish)"
    echo "set -g -x fish_greeting ''" >> ~/.config/fish/config.fish
    echo "set -g -x MISE_DATA_DIR '~/mise_data'"
    echo "alias v \"nvim\"" >> ~/.config/fish/config.fish
    echo "alias yy \"yazi\"" >> ~/.config/fish/config.fish
    echo "alias x \"exit\"" >> ~/.config/fish/config.fish
    echo "alias lg \"lazygit\"" >> ~/.config/fish/config.fish
    echo "zoxide init fish | source" >> ~/.config/fish/config.fish
    echo '~/.local/bin/mise activate fish | source' >> ~/.config/fish/config.fish
    @curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish
    @omf install agnoster


#install programming languages
install-programming-languages:
   @echo "Installing languages using mise"
   @mise install node
   @mise use -g node
   @mise install go
   @mise use -g go
