# x11
[[manager.prepend_keymap]]
on  = "y"
run = [ '''
	shell 'echo "file://$@" | xclip -i -selection clipboard -t text/uri-list' --confirm
''', "yank" ]

# wayland
# [[manager.prepend_keymap]]
# on  = "y"
# run = [ '''
# 	shell 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list' --confirm 
# ''', "yank" ]
